# Generated by Django 3.0.4 on 2020-03-27 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodrecipe', '0004_auto_20200327_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user',
            new_name='owner',
        ),
    ]
